/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using:
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_adressef_Source
#define SOM_Module_adressef_Source
#endif
#define AdresseF_Class_Source
#define M_AdresseF_Class_Source

#include "ADRESSEF.ih"
#include "ADRESSEF.rh"

SOM_Scope MRESULT SOMLINK adressef_wpDragOver (AdresseF* somSelf,
                                               HWND      hwndCnr,
                                               PDRAGINFO pdrgInfo)
   {
   BOOL      f ;
   CHAR      sz [CCHMAXPATH] ;
   PDRAGITEM pditem ;
   ULONG     ul ;

   f = TRUE ;
   for  (ul = 0; ul < pdrgInfo->cditem; ul++)
        {
        pditem = DrgQueryDragitemPtr (pdrgInfo,
                                      ul) ;
        DrgQueryStrName (pditem->hstrType,
                         sizeof (sz),
                         sz) ;
        if   (!strstr (sz,
                       "DRT_ADRESSE"))
             {
             f = FALSE ;
             break ;
             }
        }
   return (f) ? MRFROM2SHORT (DOR_DROP, pdrgInfo->usOperation) : MRFROM2SHORT (DOR_NEVERDROP, pdrgInfo->usOperation) ;
   }

SOM_Scope void SOMLINK adressef_wpclsInitData (M_AdresseF* somSelf)
   {
   M_AdresseFData* somThis ;
   PSZ             psz ;

   somThis = M_AdresseFGetData (somSelf) ;
   M_AdresseF_parent_M_WPFolder_wpclsInitData (somSelf) ;
   psz = _somLocateClassFile (SOMClassMgrObject,
                              SOM_IdFromString (_somGetClassName (somSelf)),
                              1,
                              1) ;
   DosQueryModuleHandle (psz,
                         &_hmod) ;
   }

SOM_Scope ULONG SOMLINK adressef_wpclsQueryIconData (M_AdresseF* somSelf,
                                                     PICONINFO   pIconInfo)
   {
   M_AdresseFData* somThis ;

   somThis = M_AdresseFGetData (somSelf) ;
   if   (pIconInfo)
        {
        pIconInfo->fFormat = ICON_RESOURCE ;
        pIconInfo->hmod = _hmod ;
        pIconInfo->resid = IDN_ADRESSORDNER ;
        }
   return sizeof (ICONINFO) ;
   }

SOM_Scope ULONG SOMLINK adressef_wpclsQueryStyle (M_AdresseF* somSelf)
   {
   return (M_AdresseF_parent_M_WPFolder_wpclsQueryStyle (somSelf) | CLSSTYLE_NEVERTEMPLATE) ;
   }

SOM_Scope PSZ  SOMLINK adressef_wpclsQueryTitle(M_AdresseF *somSelf)
   {
   return "AdressOrdner" ;
   }

