
/*
 * This file was generated by the SOM Compiler.
 * FileName: ADRESSE.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 *  $Header: D:/Projekte/SOM!WPS Inside!1/Source/rcs/ADRESSE.h 1.1 1996/04/10 13:27:43 HaWi Exp $
 */


#ifndef SOM_Adresse_h
#define SOM_Adresse_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef Adresse
#define Adresse SOMObject
#endif
#include <wpabs.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_Adresse
    #define M_Adresse SOMObject
#endif /* M_Adresse */

/*
 * End of user-defined types.
 */

#define Adresse_MajorVersion 1
#define Adresse_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define AdresseNewClass adressec
#pragma linkage(adressec, system)
#define AdresseClassData adressed
#define AdresseCClassData adressex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include "ADRESSE.h"
/*--------------Migration------------*/
#define Adresse_classObj AdresseClassData.classObject
#define _Adresse Adresse_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK AdresseNewClass(integer4 somtmajorVersion,
                integer4 somtminorVersion);
#pragma linkage(AdresseNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct AdresseClassDataStructure {
        SOMClass *classObject;
} SOMDLINK AdresseClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct AdresseCClassDataStructure {
        somMethodTabs parentMtab;
        somDToken instanceDataToken;
} SOMDLINK AdresseCClassData;

/*
 * New and Renew macros for Adresse
 */
#define AdresseNew() \
   (_somNew(_Adresse ? _Adresse : AdresseNewClass(Adresse_MajorVersion, Adresse_MinorVersion)))
#define AdresseRenew(buf) \
   (_somRenew(_Adresse ? _Adresse : AdresseNewClass(Adresse_MajorVersion, Adresse_MinorVersion), buf))

/*
 * Override method: wpAddSettingsPages
 */
#define Adresse_wpAddSettingsPages(somSelf,hwndNotebook) \
        WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpFormatDragItem
 */
#define Adresse_wpFormatDragItem(somSelf,pdrgItem) \
        WPObject_wpFormatDragItem(somSelf,pdrgItem)

/*
 * Override method: wpRestoreState
 */
#define Adresse_wpRestoreState(somSelf,ulReserved) \
        WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSaveState
 */
#define Adresse_wpSaveState(somSelf) \
        WPObject_wpSaveState(somSelf)

/*
 * Override method: wpSetup
 */
#define Adresse_wpSetup(somSelf,pszSetupString) \
        WPObject_wpSetup(somSelf,pszSetupString)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define Adresse_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define Adresse_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define Adresse_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define Adresse_wpAddToObjUseList WPObject_wpAddToObjUseList
#define Adresse_wpAllocMem WPObject_wpAllocMem
#define Adresse_wpAppendObject WPObject_wpAppendObject
#define Adresse_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define Adresse_wpClose WPObject_wpClose
#define Adresse_wpCnrInsertObject WPObject_wpCnrInsertObject
#define Adresse_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define Adresse_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define Adresse_wpConfirmDelete WPObject_wpConfirmDelete
#define Adresse_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define Adresse_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define Adresse_wpCopyObject WPObject_wpCopyObject
#define Adresse_wpCreateAnother WPObject_wpCreateAnother
#define Adresse_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define Adresse_wpCreateShadowObject WPObject_wpCreateShadowObject
#define Adresse_wpDelete WPObject_wpDelete
#define Adresse_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define Adresse_wpDisplayHelp WPObject_wpDisplayHelp
#define Adresse_wpDisplayMenu WPObject_wpDisplayMenu
#define Adresse_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define Adresse_wpDraggedOverObject WPObject_wpDraggedOverObject
#define Adresse_wpDragOver WPObject_wpDragOver
#define Adresse_wpDrop WPObject_wpDrop
#define Adresse_wpDroppedOnObject WPObject_wpDroppedOnObject
#define Adresse_wpEndConversation WPObject_wpEndConversation
#define Adresse_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define Adresse_wpFindUseItem WPObject_wpFindUseItem
#define Adresse_wpFree WPObject_wpFree
#define Adresse_wpFreeMem WPObject_wpFreeMem
#define Adresse_wpHide WPObject_wpHide
#define Adresse_wpInitData WPObject_wpInitData
#define Adresse_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define Adresse_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define Adresse_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define Adresse_wpMenuItemSelected WPObject_wpMenuItemSelected
#define Adresse_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define Adresse_wpMoveObject WPObject_wpMoveObject
#define Adresse_wpOpen WPObject_wpOpen
#define Adresse_wpPrintObject WPObject_wpPrintObject
#define Adresse_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define Adresse_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define Adresse_wpQueryConfirmations WPObject_wpQueryConfirmations
#define Adresse_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define Adresse_wpQueryDefaultView WPObject_wpQueryDefaultView
#define Adresse_wpQueryDetailsData WPObject_wpQueryDetailsData
#define Adresse_wpQueryError WPObject_wpQueryError
#define Adresse_wpSetFolder WPObject_wpSetFolder
#define Adresse_wpQueryFolder WPObject_wpQueryFolder
#define Adresse_wpQueryIcon WPObject_wpQueryIcon
#define Adresse_wpQueryIconData WPObject_wpQueryIconData
#define Adresse_wpQueryMinWindow WPObject_wpQueryMinWindow
#define Adresse_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define Adresse_wpQueryStyle WPObject_wpQueryStyle
#define Adresse_wpSetTaskRec WPObject_wpSetTaskRec
#define Adresse_wpFindTaskRec WPObject_wpFindTaskRec
#define Adresse_wpQueryTitle WPObject_wpQueryTitle
#define Adresse_wpRegisterView WPObject_wpRegisterView
#define Adresse_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define Adresse_wpRender WPObject_wpRender
#define Adresse_wpRenderComplete WPObject_wpRenderComplete
#define Adresse_wpReplaceObject WPObject_wpReplaceObject
#define Adresse_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define Adresse_wpRestore WPObject_wpRestore
#define Adresse_wpRestoreData WPObject_wpRestoreData
#define Adresse_wpRestoreLong WPObject_wpRestoreLong
#define Adresse_wpRestoreString WPObject_wpRestoreString
#define Adresse_wpSaveData WPObject_wpSaveData
#define Adresse_wpSaveImmediate WPObject_wpSaveImmediate
#define Adresse_wpSaveDeferred WPObject_wpSaveDeferred
#define Adresse_wpSaveLong WPObject_wpSaveLong
#define Adresse_wpSaveString WPObject_wpSaveString
#define Adresse_wpScanSetupString WPObject_wpScanSetupString
#define Adresse_wpSetConcurrentView WPObject_wpSetConcurrentView
#define Adresse_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define Adresse_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define Adresse_wpSetDefaultView WPObject_wpSetDefaultView
#define Adresse_wpSetError WPObject_wpSetError
#define Adresse_wpSetIconHandle WPObject_wpSetIconHandle
#define Adresse_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define Adresse_wpSetupOnce WPObject_wpSetupOnce
#define Adresse_wpSetIcon WPObject_wpSetIcon
#define Adresse_wpSetIconData WPObject_wpSetIconData
#define Adresse_wpSetMinWindow WPObject_wpSetMinWindow
#define Adresse_wpSetStyle WPObject_wpSetStyle
#define Adresse_wpModifyStyle WPObject_wpModifyStyle
#define Adresse_wpSetTitle WPObject_wpSetTitle
#define Adresse_wpSwitchTo WPObject_wpSwitchTo
#define Adresse_wpUnInitData WPObject_wpUnInitData
#define Adresse_wpViewObject WPObject_wpViewObject
#define Adresse_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define Adresse_wpQueryHandle WPObject_wpQueryHandle
#define Adresse_wpUnlockObject WPObject_wpUnlockObject
#define Adresse_wpObjectReady WPObject_wpObjectReady
#define Adresse_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define Adresse_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define Adresse_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define Adresse_wpIsDeleteable WPObject_wpIsDeleteable
#define Adresse_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define Adresse_wpSetObjectID WPObject_wpSetObjectID
#define Adresse_wpQueryObjectID WPObject_wpQueryObjectID
#define Adresse_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define Adresse_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define Adresse_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define Adresse_wpFindViewItem WPObject_wpFindViewItem
#define Adresse_wpLockObject WPObject_wpLockObject
#define Adresse_wpIsLocked WPObject_wpIsLocked
#define Adresse_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define Adresse_wpWaitForClose WPObject_wpWaitForClose
#define Adresse_somDefaultInit SOMObject_somDefaultInit
#define Adresse_somDestruct SOMObject_somDestruct
#define Adresse_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define Adresse_somDefaultAssign SOMObject_somDefaultAssign
#define Adresse_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define Adresse_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define Adresse_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define Adresse_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define Adresse_somDefaultVAssign SOMObject_somDefaultVAssign
#define Adresse_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define Adresse_somInit SOMObject_somInit
#define Adresse_somFree SOMObject_somFree
#define Adresse_somUninit SOMObject_somUninit
#define Adresse_somGetClass SOMObject_somGetClass
#define Adresse_somGetClassName SOMObject_somGetClassName
#define Adresse_somGetSize SOMObject_somGetSize
#define Adresse_somIsA SOMObject_somIsA
#define Adresse_somIsInstanceOf SOMObject_somIsInstanceOf
#define Adresse_somRespondsTo SOMObject_somRespondsTo
#define Adresse_somDispatch SOMObject_somDispatch
#define Adresse_somClassDispatch SOMObject_somClassDispatch
#define Adresse_somCastObj SOMObject_somCastObj
#define Adresse_somResetObj SOMObject_somResetObj
#define Adresse_somDispatchV SOMObject_somDispatchV
#define Adresse_somDispatchL SOMObject_somDispatchL
#define Adresse_somDispatchA SOMObject_somDispatchA
#define Adresse_somDispatchD SOMObject_somDispatchD
#define Adresse_somPrintSelf SOMObject_somPrintSelf
#define Adresse_somDumpSelf SOMObject_somDumpSelf
#define Adresse_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_Adresse_h */

#ifndef SOM_M_Adresse_h
#define SOM_M_Adresse_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_Adresse
#define M_Adresse SOMObject
#endif
#include <wpabs.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_Adresse_MajorVersion 1
#define M_Adresse_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_AdresseNewClass adressec
#pragma linkage(adressec, system)
#define M_AdresseClassData adressed
#define M_AdresseCClassData adressex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_Adresse_classObj M_AdresseClassData.classObject
#define _M_Adresse M_Adresse_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_AdresseNewClass(integer4 somtmajorVersion,
                integer4 somtminorVersion);
#pragma linkage(M_AdresseNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_AdresseClassDataStructure {
        SOMClass *classObject;
        somMToken clsQueryHini;
        somMToken clsQueryHmod;
} SOMDLINK M_AdresseClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_AdresseCClassDataStructure {
        somMethodTabs parentMtab;
        somDToken instanceDataToken;
} SOMDLINK M_AdresseCClassData;

/*
 * New and Renew macros for M_Adresse
 */
#define M_AdresseNew() \
   (_somNew(_M_Adresse ? _M_Adresse : M_AdresseNewClass(M_Adresse_MajorVersion, M_Adresse_MinorVersion)))
#define M_AdresseRenew(buf) \
   (_somRenew(_M_Adresse ? _M_Adresse : M_AdresseNewClass(M_Adresse_MajorVersion, M_Adresse_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_Adresse_wpclsInitData(somSelf) \
        M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_Adresse_wpclsQueryDefaultView(somSelf) \
        M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_Adresse_wpclsQueryIconData(somSelf,pIconInfo) \
        M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryTitle
 */
#define M_Adresse_wpclsQueryTitle(somSelf) \
        M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_Adresse_wpclsUnInitData(somSelf) \
        M_WPObject_wpclsUnInitData(somSelf)

/*
 * New Method: clsQueryHini
 */
typedef ULONG   SOMLINK somTP_M_Adresse_clsQueryHini(M_Adresse *somSelf);
#pragma linkage(somTP_M_Adresse_clsQueryHini, system)
typedef somTP_M_Adresse_clsQueryHini *somTD_M_Adresse_clsQueryHini;
#define somMD_M_Adresse_clsQueryHini "::M_Adresse::clsQueryHini"
#define M_Adresse_clsQueryHini(somSelf) \
    (SOM_Resolve(somSelf, M_Adresse, clsQueryHini) \
        (somSelf))
#ifndef SOMGD_clsQueryHini
    #if (defined(_clsQueryHini) || defined(__clsQueryHini))
        #undef _clsQueryHini
        #undef __clsQueryHini
        #define SOMGD_clsQueryHini 1
    #else
        #define _clsQueryHini M_Adresse_clsQueryHini
    #endif /* _clsQueryHini */
#endif /* SOMGD_clsQueryHini */

/*
 * New Method: clsQueryHmod
 */
typedef ULONG   SOMLINK somTP_M_Adresse_clsQueryHmod(M_Adresse *somSelf);
#pragma linkage(somTP_M_Adresse_clsQueryHmod, system)
typedef somTP_M_Adresse_clsQueryHmod *somTD_M_Adresse_clsQueryHmod;
#define somMD_M_Adresse_clsQueryHmod "::M_Adresse::clsQueryHmod"
#define M_Adresse_clsQueryHmod(somSelf) \
    (SOM_Resolve(somSelf, M_Adresse, clsQueryHmod) \
        (somSelf))
#ifndef SOMGD_clsQueryHmod
    #if (defined(_clsQueryHmod) || defined(__clsQueryHmod))
        #undef _clsQueryHmod
        #undef __clsQueryHmod
        #define SOMGD_clsQueryHmod 1
    #else
        #define _clsQueryHmod M_Adresse_clsQueryHmod
    #endif /* _clsQueryHmod */
#endif /* SOMGD_clsQueryHmod */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_Adresse_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_Adresse_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_Adresse_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_Adresse_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_Adresse_wpclsNew M_WPObject_wpclsNew
#define M_Adresse_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_Adresse_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_Adresse_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_Adresse_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_Adresse_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_Adresse_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_Adresse_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_Adresse_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_Adresse_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_Adresse_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_Adresse_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_Adresse_wpclsSetError M_WPObject_wpclsSetError
#define M_Adresse_wpclsQueryError M_WPObject_wpclsQueryError
#define M_Adresse_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_Adresse_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_Adresse_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_Adresse_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_Adresse_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_Adresse_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_Adresse_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_Adresse_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_Adresse_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_Adresse_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_Adresse_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_Adresse_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_Adresse__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_Adresse__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_Adresse__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_Adresse__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_Adresse_somNew SOMClass_somNew
#define M_Adresse_somNewNoInit SOMClass_somNewNoInit
#define M_Adresse_somRenew SOMClass_somRenew
#define M_Adresse_somRenewNoInit SOMClass_somRenewNoInit
#define M_Adresse_somRenewNoZero SOMClass_somRenewNoZero
#define M_Adresse_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_Adresse_somAllocate SOMClass_somAllocate
#define M_Adresse_somDeallocate SOMClass_somDeallocate
#define M_Adresse__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_Adresse__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_Adresse_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_Adresse_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_Adresse_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_Adresse_somInitClass SOMClass_somInitClass
#define M_Adresse_somInitMIClass SOMClass_somInitMIClass
#define M_Adresse_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_Adresse_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_Adresse_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_Adresse_somClassReady SOMClass_somClassReady
#define M_Adresse_somGetApplyStub SOMClass_somGetApplyStub
#define M_Adresse_somGetClassData SOMClass_somGetClassData
#define M_Adresse_somSetClassData SOMClass_somSetClassData
#define M_Adresse_somGetClassMtab SOMClass_somGetClassMtab
#define M_Adresse_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_Adresse_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_Adresse_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_Adresse_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_Adresse_somGetMemberToken SOMClass_somGetMemberToken
#define M_Adresse_somGetMethodData SOMClass_somGetMethodData
#define M_Adresse_somGetRdStub SOMClass_somGetRdStub
#define M_Adresse_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_Adresse_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_Adresse_somGetMethodToken SOMClass_somGetMethodToken
#define M_Adresse_somGetName SOMClass_somGetName
#define M_Adresse_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_Adresse_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_Adresse_somGetNumMethods SOMClass_somGetNumMethods
#define M_Adresse_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_Adresse_somGetParent SOMClass_somGetParent
#define M_Adresse_somGetParents SOMClass_somGetParents
#define M_Adresse_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_Adresse_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_Adresse_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_Adresse_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_Adresse_somFindMethod SOMClass_somFindMethod
#define M_Adresse_somFindMethodOk SOMClass_somFindMethodOk
#define M_Adresse_somFindSMethod SOMClass_somFindSMethod
#define M_Adresse_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_Adresse_somLookupMethod SOMClass_somLookupMethod
#define M_Adresse_somCheckVersion SOMClass_somCheckVersion
#define M_Adresse_somDescendedFrom SOMClass_somDescendedFrom
#define M_Adresse_somSupportsMethod SOMClass_somSupportsMethod
#define M_Adresse_somDefinedMethod SOMClass_somDefinedMethod
#define M_Adresse_somOverrideMtab SOMClass_somOverrideMtab
#define M_Adresse_somDefaultInit SOMObject_somDefaultInit
#define M_Adresse_somDestruct SOMObject_somDestruct
#define M_Adresse_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_Adresse_somDefaultAssign SOMObject_somDefaultAssign
#define M_Adresse_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_Adresse_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_Adresse_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_Adresse_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_Adresse_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_Adresse_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_Adresse_somInit SOMObject_somInit
#define M_Adresse_somFree SOMObject_somFree
#define M_Adresse_somUninit SOMObject_somUninit
#define M_Adresse_somGetClass SOMObject_somGetClass
#define M_Adresse_somGetClassName SOMObject_somGetClassName
#define M_Adresse_somGetSize SOMObject_somGetSize
#define M_Adresse_somIsA SOMObject_somIsA
#define M_Adresse_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_Adresse_somRespondsTo SOMObject_somRespondsTo
#define M_Adresse_somDispatch SOMObject_somDispatch
#define M_Adresse_somClassDispatch SOMObject_somClassDispatch
#define M_Adresse_somCastObj SOMObject_somCastObj
#define M_Adresse_somResetObj SOMObject_somResetObj
#define M_Adresse_somDispatchV SOMObject_somDispatchV
#define M_Adresse_somDispatchL SOMObject_somDispatchL
#define M_Adresse_somDispatchA SOMObject_somDispatchA
#define M_Adresse_somDispatchD SOMObject_somDispatchD
#define M_Adresse_somPrintSelf SOMObject_somPrintSelf
#define M_Adresse_somDumpSelf SOMObject_somDumpSelf
#define M_Adresse_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_Adresse_h */
