/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using:
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_adresse_Source
#define SOM_Module_adresse_Source
#endif
#define Adresse_Class_Source
#define M_Adresse_Class_Source

#include "ADRESSE.ih"
#include "ADRESSE.rh"

MRESULT EXPENTRY Adresse1DlgWndProc (HWND   hwndDlg,
                                     ULONG  msg,
                                     MPARAM mp1,
                                     MPARAM mp2)
   {
   switch (msg)
      {
      case WM_DESTROY:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;

           somSelf = WinQueryWindowPtr (hwndDlg,
                                        QWL_USER) ;
           somThis = AdresseGetData (somSelf) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD01,
                                sizeof (_szField01),
                                _szField01) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD02,
                                sizeof (_szField02),
                                _szField02) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD03,
                                sizeof (_szField03),
                                _szField03) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD04,
                                sizeof (_szField04),
                                _szField04) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD05,
                                sizeof (_szField05),
                                _szField05) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD06,
                                sizeof (_szField06),
                                _szField06) ;
           break ;
           }
      case WM_INITDLG:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;
           CHAR         sz [65] ;
           HINI         hini ;

           somSelf = PVOIDFROMMP (mp2) ;
           somThis = AdresseGetData (somSelf) ;
           WinSetWindowPtr (hwndDlg,
                            QWL_USER,
                            somSelf) ;
           hini = adresse_clsQueryHini (_somGetClass (somSelf)) ;
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field01",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD01,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field02",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD02,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field03",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD03,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field04",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD04,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field05",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD05,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field06",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD06,
                                   sz) ;
                }
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD01,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField01) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD01,
                              _szField01) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD02,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField02) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD02,
                              _szField02) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD03,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField03) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD03,
                              _szField03) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD04,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField04) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD04,
                              _szField04) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD05,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField05) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD05,
                              _szField05) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD06,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField06) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD06,
                              _szField06) ;
           return (MRESULT) FALSE ;
           }
      }
   return WinDefDlgProc (hwndDlg,
                         msg,
                         mp1,
                         mp2) ;
   }

MRESULT EXPENTRY Adresse2DlgWndProc (HWND   hwndDlg,
                                     ULONG  msg,
                                     MPARAM mp1,
                                     MPARAM mp2)
   {
   switch (msg)
      {
      case WM_DESTROY:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;

           somSelf = WinQueryWindowPtr (hwndDlg,
                                        QWL_USER) ;
           somThis = AdresseGetData (somSelf) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD07,
                                sizeof (_szField07),
                                _szField07) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD08,
                                sizeof (_szField08),
                                _szField08) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD09,
                                sizeof (_szField09),
                                _szField09) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD10,
                                sizeof (_szField10),
                                _szField10) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD11,
                                sizeof (_szField11),
                                _szField11) ;
           WinQueryDlgItemText (hwndDlg,
                                IDE_FIELD12,
                                sizeof (_szField12),
                                _szField12) ;
           break ;
           }
      case WM_INITDLG:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;
           CHAR         sz [65] ;
           HINI         hini ;

           somSelf = PVOIDFROMMP (mp2) ;
           somThis = AdresseGetData (somSelf) ;
           WinSetWindowPtr (hwndDlg,
                            QWL_USER,
                            somSelf) ;
           hini = adresse_clsQueryHini (_somGetClass (somSelf)) ;
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field07",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD07,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field08",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD08,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field09",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD09,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field10",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD10,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field11",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD11,
                                   sz) ;
                }
           if   (PrfQueryProfileString (hini,
                                        "Adresse",
                                        "Field12",
                                        NULL,
                                        sz,
                                        sizeof (sz)))
                {
                WinSetDlgItemText (hwndDlg,
                                   IDT_FIELD12,
                                   sz) ;
                }
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD07,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField07) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD07,
                              _szField07) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD08,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField08) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD08,
                              _szField08) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD09,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField09) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD09,
                              _szField09) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD10,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField10) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD10,
                              _szField10) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD11,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField11) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD11,
                              _szField11) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_FIELD12,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (sizeof (_szField12) - 1),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDE_FIELD12,
                              _szField12) ;
           return (MRESULT) FALSE ;
           }
      }
   return WinDefDlgProc (hwndDlg,
                         msg,
                         mp1,
                         mp2) ;
   }

MRESULT EXPENTRY BemerkungDlgWndProc (HWND   hwndDlg,
                                      ULONG  msg,
                                      MPARAM mp1,
                                      MPARAM mp2)
   {
   switch (msg)
      {
      case WM_DESTROY:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;

           somSelf = WinQueryWindowPtr (hwndDlg,
                                        QWL_USER) ;
           somThis = AdresseGetData (somSelf) ;
           WinQueryDlgItemText (hwndDlg,
                                IDF_BEMERKUNG,
                                sizeof (_szBemerkung),
                                _szBemerkung) ;
           break ;
           }
      case WM_INITDLG:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;

           somSelf = PVOIDFROMMP (mp2) ;
           somThis = AdresseGetData (somSelf) ;
           WinSetWindowPtr (hwndDlg,
                            QWL_USER,
                            somSelf) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDF_BEMERKUNG,
                              MLM_SETTEXTLIMIT,
                              MPFROMLONG (2047),
                              MPVOID) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDF_BEMERKUNG,
                              MLM_FORMAT,
                              MPFROMSHORT (MLFIE_NOTRANS),
                              MPVOID) ;
           WinSetDlgItemText (hwndDlg,
                              IDF_BEMERKUNG,
                              _szBemerkung) ;
           return (MRESULT) FALSE ;
           }
      }
   return WinDefDlgProc (hwndDlg,
                         msg,
                         mp1,
                         mp2) ;
   }

MRESULT EXPENTRY GlobalDlgWndProc (HWND   hwndDlg,
                                   ULONG  msg,
                                   MPARAM mp1,
                                   MPARAM mp2)
   {
   switch (msg)
      {
      case WM_CONTROL:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;
           CHAR         sz [65] ;
           CHAR         sz2 [65] ;
           CHAR         sz3 [65] ;
           HINI         hini ;
           SHORT        s ;

           somSelf = WinQueryWindowPtr (hwndDlg,
                                        QWL_USER) ;
           somThis = AdresseGetData (somSelf) ;
           hini = adresse_clsQueryHini (_somGetClass (somSelf)) ;
           switch (SHORT1FROMMP (mp1))
              {
              case IDL_KEY:
                   switch (SHORT2FROMMP (mp1))
                      {
                      case LN_SELECT:
                           if   ((s = SHORT1FROMMR (WinSendDlgItemMsg (hwndDlg,
                                                                       IDL_KEY,
                                                                       LM_QUERYSELECTION,
                                                                       MPFROMSHORT (LIT_FIRST),
                                                                       MPVOID))) != LIT_NONE)
                                {
                                WinSendDlgItemMsg (hwndDlg,
                                                   IDL_KEY,
                                                   LM_QUERYITEMTEXT,
                                                   MPFROM2SHORT (s, sizeof (sz)),
                                                   MPFROMP (sz)) ;
                                if   (*_szOldSelection)
                                     {
                                     WinQueryDlgItemText (hwndDlg,
                                                          IDE_VALUE,
                                                          sizeof (sz2),
                                                          sz2) ;
                                     PrfWriteProfileString (hini,
                                                            "Adresse",
                                                            _szOldSelection,
                                                            sz2) ;
                                     }
                                PrfQueryProfileString (hini,
                                                       "Adresse",
                                                       sz,
                                                       "",
                                                       sz3,
                                                       sizeof (sz3)) ;
                                WinSetDlgItemText (hwndDlg,
                                                   IDE_VALUE,
                                                   sz3) ;
                                strcpy (_szOldSelection,
                                        sz) ;
                                }
                           break ;
                      }
                   break ;
              }
           break ;
           }
      case WM_DESTROY:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;
           CHAR         sz [65] ;
           CHAR         sz2 [65] ;
           HINI         hini ;
           SHORT        s ;

           somSelf = WinQueryWindowPtr (hwndDlg,
                                        QWL_USER) ;
           somThis = AdresseGetData (somSelf) ;
           hini = adresse_clsQueryHini (_somGetClass (somSelf)) ;
           if   ((s = SHORT1FROMMR (WinSendDlgItemMsg (hwndDlg,
                                                       IDL_KEY,
                                                       LM_QUERYSELECTION,
                                                       MPFROMSHORT (LIT_FIRST),
                                                       MPVOID))) != LIT_NONE)
                {
                WinSendDlgItemMsg (hwndDlg,
                                   IDL_KEY,
                                   LM_QUERYITEMTEXT,
                                   MPFROM2SHORT (s, sizeof (sz)),
                                   MPFROMP (sz)) ;
                WinQueryDlgItemText (hwndDlg,
                                     IDE_VALUE,
                                     sizeof (sz2),
                                     sz2) ;
                PrfWriteProfileString (hini,
                                       "Adresse",
                                       sz,
                                       sz2) ;
                }
           break ;
           }
      case WM_INITDLG:
           {
           Adresse*     somSelf ;
           AdresseData* somThis ;
           CHAR         sz [65] ;
           ULONG        ul ;

           somSelf = PVOIDFROMMP (mp2) ;
           somThis = AdresseGetData (somSelf) ;
           WinSetWindowPtr (hwndDlg,
                            QWL_USER,
                            somSelf) ;
           WinSendDlgItemMsg (hwndDlg,
                              IDE_VALUE,
                              EM_SETTEXTLIMIT,
                              MPFROMSHORT (64),
                              MPVOID) ;
           *_szOldSelection = '\0' ;
           for  (ul = 0; ul < 12; ul++)
                {
                sprintf (sz,
                         "Field%02u",
                         ul + 1) ;
                WinSendDlgItemMsg (hwndDlg,
                                   IDL_KEY,
                                   LM_INSERTITEM,
                                   MPFROMSHORT (LIT_END),
                                   MPFROMP (sz)) ;
                }
           WinSendDlgItemMsg (hwndDlg,
                              IDL_KEY,
                              LM_SELECTITEM,
                              MPFROMSHORT (0),
                              MPFROMSHORT (TRUE)) ;
           return (MRESULT) FALSE ;
           }
      }
   return WinDefDlgProc (hwndDlg,
                         msg,
                         mp1,
                         mp2) ;
   }

SOM_Scope BOOL SOMLINK adresse_wpAddSettingsPages (Adresse* somSelf,
                                                   HWND     hwndNotebook)
   {
   BOOL     f ;
   PAGEINFO pginf ;

   f = Adresse_parent_WPAbstract_wpAddSettingsPages (somSelf,
                                                     hwndNotebook) ;
   memset (&pginf,
           0,
           sizeof (PAGEINFO)) ;
   pginf.cb = sizeof (PAGEINFO) ;
   pginf.pfnwp = GlobalDlgWndProc ;
   pginf.resid = adresse_clsQueryHmod (_somGetClass (somSelf)) ;
   pginf.pCreateParams = somSelf ;
   pginf.dlgid = IDD_GLOBAL ;
   pginf.usPageStyleFlags = BKA_MAJOR ;
   pginf.usPageInsertFlags = BKA_FIRST ;
   pginf.pszName = "Global" ;
   _wpInsertSettingsPage (somSelf,
                          hwndNotebook,
                          &pginf) ;
   memset (&pginf,
           0,
           sizeof (PAGEINFO)) ;
   pginf.cb = sizeof (PAGEINFO) ;
   pginf.pfnwp = BemerkungDlgWndProc ;
   pginf.resid = adresse_clsQueryHmod (_somGetClass (somSelf)) ;
   pginf.pCreateParams = somSelf ;
   pginf.dlgid = IDD_BEMERKUNG ;
   pginf.usPageStyleFlags = BKA_MAJOR ;
   pginf.usPageInsertFlags = BKA_FIRST ;
   pginf.pszName = "Bemerkung" ;
   _wpInsertSettingsPage (somSelf,
                          hwndNotebook,
                          &pginf) ;
   memset (&pginf,
           0,
           sizeof (PAGEINFO)) ;
   pginf.cb = sizeof (PAGEINFO) ;
   pginf.pfnwp = Adresse2DlgWndProc ;
   pginf.resid = adresse_clsQueryHmod (_somGetClass (somSelf)) ;
   pginf.pCreateParams = somSelf ;
   pginf.dlgid = IDD_ADRESSE2 ;
   pginf.usPageStyleFlags = BKA_MAJOR ;
   pginf.usPageInsertFlags = BKA_FIRST ;
   pginf.pszName = "Adresse 2" ;
   _wpInsertSettingsPage (somSelf,
                          hwndNotebook,
                          &pginf) ;
   memset (&pginf,
           0,
           sizeof (PAGEINFO)) ;
   pginf.cb = sizeof (PAGEINFO) ;
   pginf.pfnwp = Adresse1DlgWndProc ;
   pginf.resid = adresse_clsQueryHmod (_somGetClass (somSelf)) ;
   pginf.pCreateParams = somSelf ;
   pginf.dlgid = IDD_ADRESSE1 ;
   pginf.usPageStyleFlags = BKA_MAJOR ;
   pginf.usPageInsertFlags = BKA_FIRST ;
   pginf.pszName = "Adresse 1" ;
   _wpInsertSettingsPage (somSelf,
                          hwndNotebook,
                          &pginf) ;
   return f ;
   }

SOM_Scope BOOL SOMLINK adresse_wpFormatDragItem (Adresse*  somSelf,
                                                 PDRAGITEM pdrgItem)
   {
   PSZ psz = "DRT_UNKNOWN, DRT_ADRESSE" ;

   DrgDeleteStrHandle (pdrgItem->hstrType) ;
   pdrgItem->hstrType = DrgAddStrHandle (psz) ;
   return Adresse_parent_WPAbstract_wpFormatDragItem (somSelf,
                                                      pdrgItem) ;
   }

SOM_Scope BOOL SOMLINK adresse_wpRestoreState (Adresse* somSelf,
                                               ULONG    ulReserved)
   {
   AdresseData* somThis ;
   ULONG       ul ;

   somThis = AdresseGetData (somSelf) ;
   ul = sizeof (_szField01) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     1,
                     _szField01,
                     &ul) ;
   ul = sizeof (_szField02) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     2,
                     _szField02,
                     &ul) ;
   ul = sizeof (_szField03) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     3,
                     _szField03,
                     &ul) ;
   ul = sizeof (_szField04) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     4,
                     _szField04,
                     &ul) ;
   ul = sizeof (_szField05) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     5,
                     _szField05,
                     &ul) ;
   ul = sizeof (_szField06) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     6,
                     _szField06,
                     &ul) ;
   ul = sizeof (_szField07) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     7,
                     _szField07,
                     &ul) ;
   ul = sizeof (_szField08) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     8,
                     _szField08,
                     &ul) ;
   ul = sizeof (_szField09) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     9,
                     _szField09,
                     &ul) ;
   ul = sizeof (_szField10) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     10,
                     _szField10,
                     &ul) ;
   ul = sizeof (_szField11) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     11,
                     _szField11,
                     &ul) ;
   ul = sizeof (_szField12) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     12,
                     _szField12,
                     &ul) ;
   ul = sizeof (_szBemerkung) ;
   _wpRestoreString (somSelf,
                     "Adresse",
                     13,
                     _szBemerkung,
                     &ul) ;
   return Adresse_parent_WPAbstract_wpRestoreState (somSelf,
                                                    ulReserved) ;
   }

SOM_Scope BOOL SOMLINK adresse_wpSaveState (Adresse* somSelf)
   {
   AdresseData* somThis ;

   somThis = AdresseGetData (somSelf) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  1,
                  _szField01) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  2,
                  _szField02) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  3,
                  _szField03) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  4,
                  _szField04) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  5,
                  _szField05) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  6,
                  _szField06) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  7,
                  _szField07) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  8,
                  _szField08) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  9,
                  _szField09) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  10,
                  _szField10) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  11,
                  _szField11) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  12,
                  _szField12) ;
   _wpSaveString (somSelf,
                  "Adresse",
                  13,
                  _szBemerkung) ;
   return Adresse_parent_WPAbstract_wpSaveState (somSelf) ;
   }

SOM_Scope BOOL SOMLINK adresse_wpSetup (Adresse* somSelf,
                                        PSZ      pszSetupString)
   {
   AdresseData* somThis ;
   ULONG        ul ;

   somThis = AdresseGetData (somSelf) ;
   ul = sizeof (_szField01) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field01",
                       _szField01,
                       &ul) ;
   ul = sizeof (_szField02) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field02",
                       _szField02,
                       &ul) ;
   ul = sizeof (_szField03) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field03",
                       _szField03,
                       &ul) ;
   ul = sizeof (_szField04) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field04",
                       _szField04,
                       &ul) ;
   ul = sizeof (_szField05) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field05",
                       _szField05,
                       &ul) ;
   ul = sizeof (_szField06) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field06",
                       _szField06,
                       &ul) ;
   ul = sizeof (_szField07) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field07",
                       _szField07,
                       &ul) ;
   ul = sizeof (_szField08) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field08",
                       _szField08,
                       &ul) ;
   ul = sizeof (_szField09) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field09",
                       _szField09,
                       &ul) ;
   ul = sizeof (_szField10) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field10",
                       _szField10,
                       &ul) ;
   ul = sizeof (_szField11) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field11",
                       _szField11,
                       &ul) ;
   ul = sizeof (_szField12) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Field12",
                       _szField12,
                       &ul) ;
   ul = sizeof (_szBemerkung) ;
   _wpScanSetupString (somSelf,
                       pszSetupString,
                       "Bemerkung",
                       _szBemerkung,
                       &ul) ;
   return Adresse_parent_WPAbstract_wpSetup (somSelf,
                                             pszSetupString) ;
   }


SOM_Scope ULONG SOMLINK adresse_clsQueryHini (M_Adresse* somSelf)
   {
   M_AdresseData* somThis ;

   somThis = M_AdresseGetData (somSelf) ;
   return _hini ;
   }

SOM_Scope ULONG SOMLINK adresse_clsQueryHmod (M_Adresse* somSelf)
   {
   M_AdresseData* somThis ;

   somThis = M_AdresseGetData (somSelf) ;
   return _hmod ;
   }

SOM_Scope void SOMLINK adresse_wpclsInitData (M_Adresse* somSelf)
   {
   CHAR           sz [CCHMAXPATH] ;
   M_AdresseData* somThis ;
   PSZ            psz ;

   somThis = M_AdresseGetData (somSelf) ;
   M_Adresse_parent_M_WPAbstract_wpclsInitData (somSelf) ;
   psz = _somLocateClassFile (SOMClassMgrObject,
                              SOM_IdFromString (_somGetClassName (somSelf)),
                              1,
                              1) ;
   DosQueryModuleHandle (psz,
                         &_hmod) ;
   DosQueryModuleName (_hmod,
                       sizeof (sz),
                       sz) ;
   if   ((psz = strstr (sz,
                        ".DLL")) != NULL)
        {
        strcpy (psz,
                ".INI") ;
        _hini = PrfOpenProfile (WinQueryAnchorBlock (HWND_DESKTOP),
                                sz) ;
        }
   }

SOM_Scope ULONG SOMLINK adresse_wpclsQueryDefaultView (M_Adresse* somSelf)
   {
   return OPEN_SETTINGS ;
   }

SOM_Scope ULONG SOMLINK adresse_wpclsQueryIconData (M_Adresse* somSelf,
                                                    PICONINFO  pIconInfo)
   {
   M_AdresseData* somThis ;

   somThis = M_AdresseGetData (somSelf) ;
   if   (pIconInfo)
        {
        pIconInfo->fFormat = ICON_RESOURCE ;
        pIconInfo->hmod = _hmod ;
        pIconInfo->resid = IDN_ADRESSE ;
        }
   return sizeof (ICONINFO) ;
   }

SOM_Scope PSZ SOMLINK adresse_wpclsQueryTitle (M_Adresse* somSelf)
   {
   return "Adresse" ;
   }

SOM_Scope void SOMLINK adresse_wpclsUnInitData (M_Adresse* somSelf)
   {
   M_AdresseData* somThis ;

   somThis = M_AdresseGetData (somSelf) ;
   PrfCloseProfile (_hini) ;
   M_Adresse_parent_M_WPAbstract_wpclsUnInitData (somSelf) ;
   }

