
/*
 * This file was generated by the SOM Compiler.
 * FileName: ADRESSEF.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 *  $Header: D:/Projekte/SOM!WPS Inside!1/Source/rcs/ADRESSEF.h 1.1 1996/04/10 13:27:44 HaWi Exp $
 */


#ifndef SOM_AdresseF_h
#define SOM_AdresseF_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef AdresseF
#define AdresseF SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_AdresseF
    #define M_AdresseF SOMObject
#endif /* M_AdresseF */

/*
 * End of user-defined types.
 */

#define AdresseF_MajorVersion 1
#define AdresseF_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define AdresseFNewClass adressefc
#pragma linkage(adressefc, system)
#define AdresseFClassData adressefd
#define AdresseFCClassData adressefx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include "ADRESSEF.h"
/*--------------Migration------------*/
#define AdresseF_classObj AdresseFClassData.classObject
#define _AdresseF AdresseF_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK AdresseFNewClass(integer4 somtmajorVersion,
                integer4 somtminorVersion);
#pragma linkage(AdresseFNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct AdresseFClassDataStructure {
        SOMClass *classObject;
} SOMDLINK AdresseFClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct AdresseFCClassDataStructure {
        somMethodTabs parentMtab;
        somDToken instanceDataToken;
} SOMDLINK AdresseFCClassData;

/*
 * New and Renew macros for AdresseF
 */
#define AdresseFNew() \
   (_somNew(_AdresseF ? _AdresseF : AdresseFNewClass(AdresseF_MajorVersion, AdresseF_MinorVersion)))
#define AdresseFRenew(buf) \
   (_somRenew(_AdresseF ? _AdresseF : AdresseFNewClass(AdresseF_MajorVersion, AdresseF_MinorVersion), buf))

/*
 * Override method: wpDragOver
 */
#define AdresseF_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
        WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define AdresseF_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define AdresseF_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define AdresseF_wpSetFldrFont WPFolder_wpSetFldrFont
#define AdresseF_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define AdresseF_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define AdresseF_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define AdresseF_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define AdresseF_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define AdresseF_wpPopulate WPFolder_wpPopulate
#define AdresseF_wpQueryContent WPFolder_wpQueryContent
#define AdresseF_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define AdresseF_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define AdresseF_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define AdresseF_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define AdresseF_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define AdresseF_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define AdresseF_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define AdresseF_wpInitIconPosData WPFolder_wpInitIconPosData
#define AdresseF_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define AdresseF_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define AdresseF_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define AdresseF_wpSetFldrSort WPFolder_wpSetFldrSort
#define AdresseF_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define AdresseF_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define AdresseF_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define AdresseF_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define AdresseF_wpDeleteContents WPFolder_wpDeleteContents
#define AdresseF_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define AdresseF_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define AdresseF_wpSearchFolder WPFolder_wpSearchFolder
#define AdresseF_wpContainsFolders WPFolder_wpContainsFolders
#define AdresseF_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define AdresseF_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define AdresseF_wpAddToContent WPFolder_wpAddToContent
#define AdresseF_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define AdresseF_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define AdresseF_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define AdresseF_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define AdresseF_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define AdresseF_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define AdresseF_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define AdresseF_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define AdresseF_wpAddFirstChild WPFolder_wpAddFirstChild
#define AdresseF_wpSetRealName WPFileSystem_wpSetRealName
#define AdresseF_wpSetType WPFileSystem_wpSetType
#define AdresseF_wpQueryType WPFileSystem_wpQueryType
#define AdresseF_wpSetAttr WPFileSystem_wpSetAttr
#define AdresseF_wpQueryAttr WPFileSystem_wpQueryAttr
#define AdresseF_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define AdresseF_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define AdresseF_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define AdresseF_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define AdresseF_wpQueryCreation WPFileSystem_wpQueryCreation
#define AdresseF_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define AdresseF_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define AdresseF_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define AdresseF_wpQueryEASize WPFileSystem_wpQueryEASize
#define AdresseF_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define AdresseF_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define AdresseF_wpRefresh WPFileSystem_wpRefresh
#define AdresseF_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define AdresseF_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define AdresseF_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define AdresseF_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define AdresseF_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define AdresseF_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define AdresseF_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define AdresseF_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define AdresseF_wpQueryRealName WPFileSystem_wpQueryRealName
#define AdresseF_wpQueryFilename WPFileSystem_wpQueryFilename
#define AdresseF_wpQueryDisk WPFileSystem_wpQueryDisk
#define AdresseF_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define AdresseF_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define AdresseF_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define AdresseF_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define AdresseF_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define AdresseF_wpAddSettingsPages WPObject_wpAddSettingsPages
#define AdresseF_wpAddToObjUseList WPObject_wpAddToObjUseList
#define AdresseF_wpAllocMem WPObject_wpAllocMem
#define AdresseF_wpAppendObject WPObject_wpAppendObject
#define AdresseF_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define AdresseF_wpClose WPObject_wpClose
#define AdresseF_wpCnrInsertObject WPObject_wpCnrInsertObject
#define AdresseF_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define AdresseF_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define AdresseF_wpConfirmDelete WPObject_wpConfirmDelete
#define AdresseF_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define AdresseF_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define AdresseF_wpCopyObject WPObject_wpCopyObject
#define AdresseF_wpCreateAnother WPObject_wpCreateAnother
#define AdresseF_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define AdresseF_wpCreateShadowObject WPObject_wpCreateShadowObject
#define AdresseF_wpDelete WPObject_wpDelete
#define AdresseF_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define AdresseF_wpDisplayHelp WPObject_wpDisplayHelp
#define AdresseF_wpDisplayMenu WPObject_wpDisplayMenu
#define AdresseF_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define AdresseF_wpDraggedOverObject WPObject_wpDraggedOverObject
#define AdresseF_wpDrop WPObject_wpDrop
#define AdresseF_wpDroppedOnObject WPObject_wpDroppedOnObject
#define AdresseF_wpEndConversation WPObject_wpEndConversation
#define AdresseF_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define AdresseF_wpFindUseItem WPObject_wpFindUseItem
#define AdresseF_wpFormatDragItem WPObject_wpFormatDragItem
#define AdresseF_wpFree WPObject_wpFree
#define AdresseF_wpFreeMem WPObject_wpFreeMem
#define AdresseF_wpHide WPObject_wpHide
#define AdresseF_wpInitData WPObject_wpInitData
#define AdresseF_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define AdresseF_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define AdresseF_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define AdresseF_wpMenuItemSelected WPObject_wpMenuItemSelected
#define AdresseF_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define AdresseF_wpMoveObject WPObject_wpMoveObject
#define AdresseF_wpOpen WPObject_wpOpen
#define AdresseF_wpPrintObject WPObject_wpPrintObject
#define AdresseF_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define AdresseF_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define AdresseF_wpQueryConfirmations WPObject_wpQueryConfirmations
#define AdresseF_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define AdresseF_wpQueryDefaultView WPObject_wpQueryDefaultView
#define AdresseF_wpQueryDetailsData WPObject_wpQueryDetailsData
#define AdresseF_wpQueryError WPObject_wpQueryError
#define AdresseF_wpSetFolder WPObject_wpSetFolder
#define AdresseF_wpQueryFolder WPObject_wpQueryFolder
#define AdresseF_wpQueryIcon WPObject_wpQueryIcon
#define AdresseF_wpQueryIconData WPObject_wpQueryIconData
#define AdresseF_wpQueryMinWindow WPObject_wpQueryMinWindow
#define AdresseF_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define AdresseF_wpQueryStyle WPObject_wpQueryStyle
#define AdresseF_wpSetTaskRec WPObject_wpSetTaskRec
#define AdresseF_wpFindTaskRec WPObject_wpFindTaskRec
#define AdresseF_wpQueryTitle WPObject_wpQueryTitle
#define AdresseF_wpRegisterView WPObject_wpRegisterView
#define AdresseF_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define AdresseF_wpRender WPObject_wpRender
#define AdresseF_wpRenderComplete WPObject_wpRenderComplete
#define AdresseF_wpReplaceObject WPObject_wpReplaceObject
#define AdresseF_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define AdresseF_wpRestore WPObject_wpRestore
#define AdresseF_wpRestoreData WPObject_wpRestoreData
#define AdresseF_wpRestoreLong WPObject_wpRestoreLong
#define AdresseF_wpRestoreState WPObject_wpRestoreState
#define AdresseF_wpRestoreString WPObject_wpRestoreString
#define AdresseF_wpSaveData WPObject_wpSaveData
#define AdresseF_wpSaveImmediate WPObject_wpSaveImmediate
#define AdresseF_wpSaveDeferred WPObject_wpSaveDeferred
#define AdresseF_wpSaveLong WPObject_wpSaveLong
#define AdresseF_wpSaveState WPObject_wpSaveState
#define AdresseF_wpSaveString WPObject_wpSaveString
#define AdresseF_wpScanSetupString WPObject_wpScanSetupString
#define AdresseF_wpSetConcurrentView WPObject_wpSetConcurrentView
#define AdresseF_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define AdresseF_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define AdresseF_wpSetDefaultView WPObject_wpSetDefaultView
#define AdresseF_wpSetError WPObject_wpSetError
#define AdresseF_wpSetIconHandle WPObject_wpSetIconHandle
#define AdresseF_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define AdresseF_wpSetupOnce WPObject_wpSetupOnce
#define AdresseF_wpSetIcon WPObject_wpSetIcon
#define AdresseF_wpSetIconData WPObject_wpSetIconData
#define AdresseF_wpSetMinWindow WPObject_wpSetMinWindow
#define AdresseF_wpSetStyle WPObject_wpSetStyle
#define AdresseF_wpModifyStyle WPObject_wpModifyStyle
#define AdresseF_wpSetTitle WPObject_wpSetTitle
#define AdresseF_wpSetup WPObject_wpSetup
#define AdresseF_wpSwitchTo WPObject_wpSwitchTo
#define AdresseF_wpUnInitData WPObject_wpUnInitData
#define AdresseF_wpViewObject WPObject_wpViewObject
#define AdresseF_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define AdresseF_wpQueryHandle WPObject_wpQueryHandle
#define AdresseF_wpUnlockObject WPObject_wpUnlockObject
#define AdresseF_wpObjectReady WPObject_wpObjectReady
#define AdresseF_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define AdresseF_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define AdresseF_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define AdresseF_wpIsDeleteable WPObject_wpIsDeleteable
#define AdresseF_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define AdresseF_wpSetObjectID WPObject_wpSetObjectID
#define AdresseF_wpQueryObjectID WPObject_wpQueryObjectID
#define AdresseF_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define AdresseF_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define AdresseF_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define AdresseF_wpFindViewItem WPObject_wpFindViewItem
#define AdresseF_wpLockObject WPObject_wpLockObject
#define AdresseF_wpIsLocked WPObject_wpIsLocked
#define AdresseF_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define AdresseF_wpWaitForClose WPObject_wpWaitForClose
#define AdresseF_somDefaultInit SOMObject_somDefaultInit
#define AdresseF_somDestruct SOMObject_somDestruct
#define AdresseF_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define AdresseF_somDefaultAssign SOMObject_somDefaultAssign
#define AdresseF_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define AdresseF_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define AdresseF_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define AdresseF_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define AdresseF_somDefaultVAssign SOMObject_somDefaultVAssign
#define AdresseF_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define AdresseF_somInit SOMObject_somInit
#define AdresseF_somFree SOMObject_somFree
#define AdresseF_somUninit SOMObject_somUninit
#define AdresseF_somGetClass SOMObject_somGetClass
#define AdresseF_somGetClassName SOMObject_somGetClassName
#define AdresseF_somGetSize SOMObject_somGetSize
#define AdresseF_somIsA SOMObject_somIsA
#define AdresseF_somIsInstanceOf SOMObject_somIsInstanceOf
#define AdresseF_somRespondsTo SOMObject_somRespondsTo
#define AdresseF_somDispatch SOMObject_somDispatch
#define AdresseF_somClassDispatch SOMObject_somClassDispatch
#define AdresseF_somCastObj SOMObject_somCastObj
#define AdresseF_somResetObj SOMObject_somResetObj
#define AdresseF_somDispatchV SOMObject_somDispatchV
#define AdresseF_somDispatchL SOMObject_somDispatchL
#define AdresseF_somDispatchA SOMObject_somDispatchA
#define AdresseF_somDispatchD SOMObject_somDispatchD
#define AdresseF_somPrintSelf SOMObject_somPrintSelf
#define AdresseF_somDumpSelf SOMObject_somDumpSelf
#define AdresseF_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_AdresseF_h */

#ifndef SOM_M_AdresseF_h
#define SOM_M_AdresseF_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_AdresseF
#define M_AdresseF SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_AdresseF_MajorVersion 1
#define M_AdresseF_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_AdresseFNewClass adressefc
#pragma linkage(adressefc, system)
#define M_AdresseFClassData adressefd
#define M_AdresseFCClassData adressefx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_AdresseF_classObj M_AdresseFClassData.classObject
#define _M_AdresseF M_AdresseF_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_AdresseFNewClass(integer4 somtmajorVersion,
                integer4 somtminorVersion);
#pragma linkage(M_AdresseFNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_AdresseFClassDataStructure {
        SOMClass *classObject;
} SOMDLINK M_AdresseFClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_AdresseFCClassDataStructure {
        somMethodTabs parentMtab;
        somDToken instanceDataToken;
} SOMDLINK M_AdresseFCClassData;

/*
 * New and Renew macros for M_AdresseF
 */
#define M_AdresseFNew() \
   (_somNew(_M_AdresseF ? _M_AdresseF : M_AdresseFNewClass(M_AdresseF_MajorVersion, M_AdresseF_MinorVersion)))
#define M_AdresseFRenew(buf) \
   (_somRenew(_M_AdresseF ? _M_AdresseF : M_AdresseFNewClass(M_AdresseF_MajorVersion, M_AdresseF_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_AdresseF_wpclsInitData(somSelf) \
        M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_AdresseF_wpclsQueryIconData(somSelf,pIconInfo) \
        M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryStyle
 */
#define M_AdresseF_wpclsQueryStyle(somSelf) \
        M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_AdresseF_wpclsQueryTitle(somSelf) \
        M_WPObject_wpclsQueryTitle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_AdresseF_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_AdresseF_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_AdresseF_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_AdresseF_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_AdresseF_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_AdresseF_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_AdresseF_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_AdresseF_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_AdresseF_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_AdresseF_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_AdresseF_wpclsNew M_WPObject_wpclsNew
#define M_AdresseF_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_AdresseF_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_AdresseF_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_AdresseF_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_AdresseF_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_AdresseF_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_AdresseF_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_AdresseF_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_AdresseF_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_AdresseF_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_AdresseF_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_AdresseF_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_AdresseF_wpclsSetError M_WPObject_wpclsSetError
#define M_AdresseF_wpclsQueryError M_WPObject_wpclsQueryError
#define M_AdresseF_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_AdresseF_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_AdresseF_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_AdresseF_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_AdresseF_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_AdresseF_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_AdresseF_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_AdresseF_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_AdresseF_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_AdresseF_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_AdresseF_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_AdresseF_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_AdresseF__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_AdresseF__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_AdresseF__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_AdresseF__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_AdresseF_somNew SOMClass_somNew
#define M_AdresseF_somNewNoInit SOMClass_somNewNoInit
#define M_AdresseF_somRenew SOMClass_somRenew
#define M_AdresseF_somRenewNoInit SOMClass_somRenewNoInit
#define M_AdresseF_somRenewNoZero SOMClass_somRenewNoZero
#define M_AdresseF_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_AdresseF_somAllocate SOMClass_somAllocate
#define M_AdresseF_somDeallocate SOMClass_somDeallocate
#define M_AdresseF__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_AdresseF__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_AdresseF_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_AdresseF_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_AdresseF_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_AdresseF_somInitClass SOMClass_somInitClass
#define M_AdresseF_somInitMIClass SOMClass_somInitMIClass
#define M_AdresseF_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_AdresseF_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_AdresseF_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_AdresseF_somClassReady SOMClass_somClassReady
#define M_AdresseF_somGetApplyStub SOMClass_somGetApplyStub
#define M_AdresseF_somGetClassData SOMClass_somGetClassData
#define M_AdresseF_somSetClassData SOMClass_somSetClassData
#define M_AdresseF_somGetClassMtab SOMClass_somGetClassMtab
#define M_AdresseF_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_AdresseF_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_AdresseF_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_AdresseF_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_AdresseF_somGetMemberToken SOMClass_somGetMemberToken
#define M_AdresseF_somGetMethodData SOMClass_somGetMethodData
#define M_AdresseF_somGetRdStub SOMClass_somGetRdStub
#define M_AdresseF_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_AdresseF_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_AdresseF_somGetMethodToken SOMClass_somGetMethodToken
#define M_AdresseF_somGetName SOMClass_somGetName
#define M_AdresseF_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_AdresseF_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_AdresseF_somGetNumMethods SOMClass_somGetNumMethods
#define M_AdresseF_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_AdresseF_somGetParent SOMClass_somGetParent
#define M_AdresseF_somGetParents SOMClass_somGetParents
#define M_AdresseF_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_AdresseF_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_AdresseF_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_AdresseF_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_AdresseF_somFindMethod SOMClass_somFindMethod
#define M_AdresseF_somFindMethodOk SOMClass_somFindMethodOk
#define M_AdresseF_somFindSMethod SOMClass_somFindSMethod
#define M_AdresseF_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_AdresseF_somLookupMethod SOMClass_somLookupMethod
#define M_AdresseF_somCheckVersion SOMClass_somCheckVersion
#define M_AdresseF_somDescendedFrom SOMClass_somDescendedFrom
#define M_AdresseF_somSupportsMethod SOMClass_somSupportsMethod
#define M_AdresseF_somDefinedMethod SOMClass_somDefinedMethod
#define M_AdresseF_somOverrideMtab SOMClass_somOverrideMtab
#define M_AdresseF_somDefaultInit SOMObject_somDefaultInit
#define M_AdresseF_somDestruct SOMObject_somDestruct
#define M_AdresseF_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_AdresseF_somDefaultAssign SOMObject_somDefaultAssign
#define M_AdresseF_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_AdresseF_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_AdresseF_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_AdresseF_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_AdresseF_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_AdresseF_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_AdresseF_somInit SOMObject_somInit
#define M_AdresseF_somFree SOMObject_somFree
#define M_AdresseF_somUninit SOMObject_somUninit
#define M_AdresseF_somGetClass SOMObject_somGetClass
#define M_AdresseF_somGetClassName SOMObject_somGetClassName
#define M_AdresseF_somGetSize SOMObject_somGetSize
#define M_AdresseF_somIsA SOMObject_somIsA
#define M_AdresseF_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_AdresseF_somRespondsTo SOMObject_somRespondsTo
#define M_AdresseF_somDispatch SOMObject_somDispatch
#define M_AdresseF_somClassDispatch SOMObject_somClassDispatch
#define M_AdresseF_somCastObj SOMObject_somCastObj
#define M_AdresseF_somResetObj SOMObject_somResetObj
#define M_AdresseF_somDispatchV SOMObject_somDispatchV
#define M_AdresseF_somDispatchL SOMObject_somDispatchL
#define M_AdresseF_somDispatchA SOMObject_somDispatchA
#define M_AdresseF_somDispatchD SOMObject_somDispatchD
#define M_AdresseF_somPrintSelf SOMObject_somPrintSelf
#define M_AdresseF_somDumpSelf SOMObject_somDumpSelf
#define M_AdresseF_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_AdresseF_h */
